### ISSUE TITLE
List of organizations is empty after configuring plugin

### ISSUE THREAD

**Issue by acorbi** [opendata-swiss/wp-ckan-backend#6]
I have configured the wp-config.php file as stated in README.md adding:

```
define( 'CKAN_API_ENDPOINT', 'https://data.opendevelopmentmekong.net/api/3/action/' );
define( 'CKAN_API_KEY', 'VALID_ADMIN_KEY' ); // ckan admin user api key

$language_priority = array(
    1 => 'en',
    2 => 'km',
    3 => 'th',
    4 => 'my',
    5 => 'vi'
);
```

When I go to **Organizations > All organizations** on the WP dashboardm the list is empty, however on https://data.opendevelopmentmekong.net/organization/ there are 6 organizations which I expect to appear on the WP dashboard.

@metaodi am I missing any steps? Do you have any logging mechanism implemented? If not, I could work on a PR to help debug this kind of things...

**Comment by tschortsch** [comment]
Right now this plugin just implements a one way sync from WordPress to CKAN. It is meant that all data (datasets, organizations, groups) is created through the WordPress admin interface. Our main goal was to replace the CKAN backend completely.

**Comment by acorbi** [comment]
Thanks @tschortsch for the clarification. 

> Right now this plugin just implements a one way sync from WordPress to CKAN

However datasets can be imported from CKAN to WP via **Datasets > Import**, can't they?

**Comment by tschortsch** [comment]
Thats right, you can import datasets into the WP backend if you have them in a valid DCAT-AP Switzerland XML format.
Important to know is that WordPress tries to create them on your CKAN instance even if they already exist there. This is done since WordPress doesn't know the package id of the dataset in CKAN.
Long story short the import isn't meant to transfer already existing CKAN datasets to WordPress but to import datasets from another OpenData platform.

**Comment by acorbi** [comment]
Ok, thanks for the details @tschortsch.

I'm closing this Issue, I think having bi-directional sync mechanism would be extraordinary (and almost a must) for fulfilling our requirements at https://github.com/OpenDevelopmentMekong but I understand that can involve a major milestone, so I'm not opening an Issue yet ;-)
